id = "mojo"
name = "Mojo"
description = "Modern Mojo language support with v0.25.6+ syntax"
version = "0.1.0"
schema_version = 1
authors = ["nijaru"]
repository = "https://github.com/nijaru/zed-mojo"

[grammars.mojo]
repository = "https://github.com/nijaru/zed-mojo"
commit = "1773161c96cbd416d06bf312685a2e41e0c25008"

[language_servers.mojo-lsp]
name = "mojo-lsp"
language = "Mojo"