name = "Mojo"
grammar = "mojo"
path_suffixes = ["mojo", "ðŸ”¥"]
language_servers = ["mojo-lsp"]
scope = "source.mojo"

[comments]
line_comment = "#"

brackets = [
  { start = "(", end = ")", close = true, newline = false },
  { start = "[", end = "]", close = true, newline = false },
  { start = "{", end = "}", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false },
  { start = "'", end = "'", close = true, newline = false },
]

[indent]
unit = "    "

[prettier]
allowed = false